name: 'Terraform check'
on:
  push:
permissions:
  id-token: write
  contents: write
jobs:
  check:
    uses: nationalarchives/dr2-github-actions/.github/workflows/terraform_check.yml@main
    secrets:
      MANAGEMENT_ACCOUNT: ${{ secrets.DR2_MANAGEMENT_ACCOUNT }}
      WORKFLOW_TOKEN: ${{ secrets.DR2_WORKFLOW_PAT }}
      STATE_BUCKET: ${{ secrets.DR2_INTG_STATE_BUCKET }}
      DYNAMO_TABLE: ${{ secrets.DR2_INTG_DYNAMO_TABLE }}
      TERRAFORM_ROLE: ${{ secrets.DR2_INTG_TERRAFORM_ROLE }}
